### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by IvBaranov** [IvBaranov/MaterialLetterIcon#1]
**Basic look**
- [x] draw circle
- [x] draw letter
- [x] set circle color
- [x] set letter color
- [x] set letter size

**Extra**
- [x] draw rect?
- [x] set letter typeface
- [x] example app
- [x] handle multiple letters to display
